version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: boto3
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: pylint
    versions:
    - 2.7.0
    - 2.7.1
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: urllib3
    versions:
    - 1.26.4
  - dependency-name: pytest
    versions:
    - 6.2.3
  - dependency-name: colorlog
    versions:
    - 4.8.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: ping3
    versions:
    - 2.7.0
  - dependency-name: arrow
    versions:
    - 1.0.3
